apiVersion: v1
kind: Service
metadata:
  name: financial-monitor-client
spec:
  type: LoadBalancer
  selector:
    app: financial-monitor-client
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
